# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bid_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bid_request.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x62id_request.proto\"\xa1\x01\n\nBidRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1c\n\x03imp\x18\x02 \x03(\x0b\x32\x0f.BidRequest.Imp\x12\x1e\n\x04user\x18\x03 \x01(\x0b\x32\x10.BidRequest.User\x1a#\n\x03Imp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x62idfloor\x18\x02 \x01(\x01\x1a$\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x62uyeruid\x18\x02 \x01(\tb\x06proto3')
)




_BIDREQUEST_IMP = _descriptor.Descriptor(
  name='Imp',
  full_name='BidRequest.Imp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BidRequest.Imp.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bidfloor', full_name='BidRequest.Imp.bidfloor', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=145,
)

_BIDREQUEST_USER = _descriptor.Descriptor(
  name='User',
  full_name='BidRequest.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BidRequest.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buyeruid', full_name='BidRequest.User.buyeruid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=183,
)

_BIDREQUEST = _descriptor.Descriptor(
  name='BidRequest',
  full_name='BidRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BidRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imp', full_name='BidRequest.imp', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='BidRequest.user', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BIDREQUEST_IMP, _BIDREQUEST_USER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=183,
)

_BIDREQUEST_IMP.containing_type = _BIDREQUEST
_BIDREQUEST_USER.containing_type = _BIDREQUEST
_BIDREQUEST.fields_by_name['imp'].message_type = _BIDREQUEST_IMP
_BIDREQUEST.fields_by_name['user'].message_type = _BIDREQUEST_USER
DESCRIPTOR.message_types_by_name['BidRequest'] = _BIDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BidRequest = _reflection.GeneratedProtocolMessageType('BidRequest', (_message.Message,), dict(

  Imp = _reflection.GeneratedProtocolMessageType('Imp', (_message.Message,), dict(
    DESCRIPTOR = _BIDREQUEST_IMP,
    __module__ = 'bid_request_pb2'
    # @@protoc_insertion_point(class_scope:BidRequest.Imp)
    ))
  ,

  User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
    DESCRIPTOR = _BIDREQUEST_USER,
    __module__ = 'bid_request_pb2'
    # @@protoc_insertion_point(class_scope:BidRequest.User)
    ))
  ,
  DESCRIPTOR = _BIDREQUEST,
  __module__ = 'bid_request_pb2'
  # @@protoc_insertion_point(class_scope:BidRequest)
  ))
_sym_db.RegisterMessage(BidRequest)
_sym_db.RegisterMessage(BidRequest.Imp)
_sym_db.RegisterMessage(BidRequest.User)


# @@protoc_insertion_point(module_scope)
