# Generated by Django 3.2 on 2021-04-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('bidding_cpm', models.IntegerField()),
                ('bid_quantity', models.IntegerField()),
            ],
        ),
    ]
